apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: o02jfq8ws-go-gitops
  description: This is GitOps manifest for o02jfq8ws-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=o02jfq8ws-go
    backstage.io/kubernetes-id: o02jfq8ws-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: o02jfq8ws-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:o02jfq8ws-go
