apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: o02jfq8ws-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: o02jfq8ws-go 
  name: o02jfq8ws-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: o02jfq8ws-go 
